### ISSUE TITLE
Setting styles with `@layer` doesn’t work

### ISSUE THREAD

**Issue by knowler** [enhance-dev/enhance-style-transform#1]
This works fine:

```html
<style>
@layer elements, page;
</style>
```

This doesn’t work:

```html
<style>
@layer elements {
  :host {
    /* some styles */
  }
}
</style>
```

I get this error message: `undefined:4:9: missing '}'`

If I change the selector inside of the `@layer` to be something else (like an element):

```html
<style>
@layer elements {
  label {
    /* some styles */
  }
}
</style>
```

I get this error message: `undefined:4:14: property missing ':'`

**Comment by ryanblock** [comment]
Looks like this issue can probably be traced back to this issue in [`css`](https://www.npmjs.com/package/css): https://github.com/reworkcss/css/issues/165

**Comment by ryanbethel** [comment]
@knowler Thanks for reporting the bug. Like @ryanblock mentioned this is caused by the css parser we use. We are discussing how best to fix it.
